# SITE CONFIGURATION
title: Brouette Labs
description: Brouette Labs
url: https://brouette-labs.com
twitter:
    username: Brouette_Labs
logo: /img/avatar.png
social:
    name: Brouette Labs
    links:
        - https://twitter.com/Brouette_Labs
        - https://github.com/brouette-labs
baseurl: ""

# LANGUAGE-SPECIFIC CONFIGURATION
default_lang: fr
languages: ["fr", "en"]
exclude_from_localizations: ["authors", "css", "fonts", "img", "js"]
localized_posts_dir: _posts

# THEME-SPECIFIC CONFIGURATION
theme_settings:
    # Meta
    # title: Eleven Labs - Le Blog
    brand : Brouette Labs
    gravatar:
    description: A website with blog posts and pages

    # Header and footer
    header_text_bg_image: /img/bg-header.png
    footer_text: Une blog, une brouette

    # Icons
    rss: /feed.xml
    email_address:
    behance:
    bitbucket:
    dribbble:
    facebook:
    flickr:
    github: brouette-labs
    google_plus:
    instagram:
    linkedin:
    pinterest:
    reddit:
    soundcloud:
    stack_exchange:
    steam:
    tumblr:
    twitter: Brouette_Labs
    wordpress:
    youtube:
    corporate:
    corporate_logo:

    # Scripts
    google_analytics: UA-99013054-5
    disqus_shortname: blog_brouette_labs
    muut_community_name:

    # Post navigation
    post_navigation: false

    # Share button
    share_button: true

# PAGINATION
paginate: 10
paginate_path: "/page/:num/"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
    sass_dir: _sass
    style: :compressed
plugins:
    - jekyll-paginate
    - jekyll-multiple-languages-plugin
    - jekyll-seo-tag
    - algoliasearch-jekyll
    - jekyll-feed
    - amp-jekyll
    - uglifier
exclude:
    - CNAME
    - CODE_OF_CONDUCT.md
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - Rakefile
    - _authors/TEMPLATE-AUTOR
    - bin
    - vendor
    - docker-compose.yml

collections:
  authors:
    output: true
